"""create todos tables

Revision ID: 49bd5fb82e41
Revises: 4b19a5c32de3
Create Date: 2025-06-15 16:50:50.925685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49bd5fb82e41'
down_revision: Union[str, None] = '4b19a5c32de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('title', sa.String(), nullable=False))
    op.drop_column('todos', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('name', sa.VARCHAR(), nullable=False))
    op.drop_column('todos', 'title')
    # ### end Alembic commands ###
